image: registry.gitlab.com/lorepub/moot/moot-build-image:latest

stages:
  - build

cache:
  key: global-cache
  # key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .stack-work/
    - /root/.stack/

build:
  stage: build
  script: |
        make build
  tags:
    - moot
