sudo: false
language: generic

services:
  - postgresql

addons:
  apt:
    packages:
      - libgmp-dev
      - postgresql-client
      - postgresql-server-dev-all

  postgresql: "9.6"

before_install:
  - cd frontend
  - npm install
  - cd ..

install:
  # stack
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.6.1/stack-1.6.1-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --no-terminal --version
  - stack install happy
  - stack install alex
  # backend
  - stack install yesod-bin
  # database
  - echo "CREATE USER moot WITH PASSWORD 'moot';" | psql postgres
  - createdb -O moot moot

# build frontend
before_script:
  - cd frontend
  - npm run-script build
  - cd ..

script:
  - stack setup
  - stack update
  - stack build
  - stack test

cache:
  timeout: 2000
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.stack
  - .stack-work/
